@startuml
'https://plantuml.com/activity-diagram-beta

start
note : Utilisateur est connecté
note : Page actuelle : Page\nde détail d'un restaurant

:Utilisateur clique sur le bouton like du Restaurant;


stop

@enduml
