@startuml
'https://plantuml.com/activity-diagram-beta

start
:Utilisateur ouvre l'application;
if (Utilisateur est-il déjà connecté ?) then (oui)
else (non)
:Utilisateur clique sur "Connexion avec Google";
:Utilisateur sélectionne son compte;
endif
:Affichage de la vue des restaurants sous forme de carte;
stop

@enduml
