@startuml
'https://plantuml.com/activity-diagram-beta

start
note : Utilisateur est connecté
:Utilisateur clique sur le bouton de menu;
:Utilisateur clique sur le bouton "Se déconnecter";
:Affichage de la page de connexion;
stop

@enduml
